# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nwf-report

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://nwfreport.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ec71041c0c58477eae1f0de768409ec8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_628330180b0546f7bca1e190f0ead4b2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nwfreport.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec71041c0c58477eae1f0de768409ec8 }}/nwf-report:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nwf-report'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_23af1b79027c43d1afe051971a6639b3 }}
        images: 'nwfreport.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec71041c0c58477eae1f0de768409ec8 }}/nwf-report:${{ github.sha }}'